# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    container_name: docker-task-db
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  app:
    build: .\app\src
    container_name: docker-task-app
    volumes:
      - .\app\src:/usr/src/app
    ports: 
      - "5001:80"